version: '3.7'

services:

  application:
    build:
      context: ./application 
      dockerfile: Dockerfile
    image: application
    container_name: application
    ports:
      - 8080:8080


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  


  
